/* eslint-disable react/no-unescaped-entities */
import { useState } from "react";
import { ArrowUpRight, CheckCircle2, Download, Github, Linkedin, Mail, Menu, X, MapPin, ExternalLink } from "lucide-react";
import { toast, Toaster } from "sonner";
import "@/App.css";

const resumeUrl = "https://customer-assets-lqy194kg.emergentagent.net/job_321bd597-5b55-450c-ae10-8c9e7bb2b155/artifacts/fo0njs51_Aman_DevOps_Resume%20%281%29.pdf";
const photoUrl = "https://customer-assets-lqy194kg.emergentagent.net/job_321bd597-5b55-450c-ae10-8c9e7bb2b155/artifacts/g6mb8v1d_picture.jpg";
const skills = ["AWS", "Kubernetes", "Docker", "Jenkins", "Terraform", "Ansible", "Prometheus", "Grafana", "Linux", "Python", "Git", "Bash"];
const experience = [{ role: "DevOps Intern", company: "Highcatch · StarAgile DevOps Training Program", date: "Jul 2025 — Dec 2025", points: ["Automated CI/CD pipelines using Jenkins and Git, reducing manual release steps.", "Containerized applications with Docker and deployed workloads on Kubernetes (EKS).", "Provisioned secure AWS infrastructure with EC2, IAM and VPC; added Ansible automation and Prometheus/Grafana dashboards."] }, { role: "Subject Matter Expert (Freelance)", company: "Chegg", date: "2023 — 2024", points: ["Delivered 120+ verified technical solutions in core Computer Science subjects.", "Maintained high accuracy, clarity and turnaround time across a high-volume workload."] }];
const projects = [{ title: "Online Ticketing & Event Management", label: "BookMyShow-like System", tags: ["Jenkins", "Docker", "EKS"], text: "A resilient deployment workflow with automatic build, test and release on every commit, plus real-time cluster monitoring." }, { title: "AWS Three-Tier Web Application", label: "Cloud architecture", tags: ["AWS", "RDS", "Terraform"], text: "A secure, highly available architecture with S3 frontend, EC2 application layer, RDS data layer, load balancing and private subnets." }, { title: "Bias in Image Generation by LLMs", label: "IEEE research publication", tags: ["Python", "ML", "DALL-E 2"], text: "A fairness study exploring gender, age, skin tone and body physique representation in diffusion-generated imagery." }];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [contactOpen, setContactOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", message: "" });
  const scrollTo = (id) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  const submitInquiry = async (e) => { e.preventDefault(); try { const response = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/inquiries`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) throw new Error("Unable to send"); setSent(true); toast.success("Thanks — your message has been received."); } catch (error) { toast.error("Could not send your message. Please try again."); } };
  return <div className="site-shell"><Toaster position="bottom-right" />
    <nav className="nav" data-testid="main-navigation"><a className="wordmark" href="#top" onClick={() => scrollTo("top")} data-testid="brand-link">AMAN<span>.</span></a><div className={`nav-links ${menuOpen ? "open" : ""}`}><button onClick={() => scrollTo("about")} data-testid="nav-about-link">About</button><button onClick={() => scrollTo("experience")} data-testid="nav-experience-link">Experience</button><button onClick={() => scrollTo("projects")} data-testid="nav-projects-link">Projects</button><button className="nav-contact" onClick={() => setContactOpen(true)} data-testid="nav-contact-button">Let's connect <ArrowUpRight size={15} /></button></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation" data-testid="mobile-menu-button">{menuOpen ? <X /> : <Menu />}</button></nav>
    <main id="top"><section className="hero container" data-testid="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> AVAILABLE FOR DEVOPS / SRE ROLES</p><h1>Building systems<br /><em>that stay up.</em></h1><p className="hero-text">I'm Aman — a DevOps & Cloud Engineer focused on dependable infrastructure, faster delivery and calmer on-call nights.</p><div className="hero-actions"><button className="button-primary" onClick={() => scrollTo("projects")} data-testid="view-work-button">View my work <ArrowUpRight size={17} /></button><a className="button-secondary" href={resumeUrl} target="_blank" rel="noreferrer" data-testid="download-resume-button"><Download size={16} /> Download resume</a></div><div className="quick-meta"><span><MapPin size={15} /> Haryana, India</span><span className="meta-rule" /><span>AWS Certified Cloud Practitioner</span></div></div><div className="hero-portrait"><div className="portrait-frame"><img src={photoUrl} alt="Aman in professional attire" data-testid="profile-photo" /><span className="portrait-badge">01 <small>/ PROFILE</small></span></div></div></section>
      <section className="intro-band" id="about"><div className="container intro-grid"><p className="section-kicker">01 / ABOUT</p><div><h2>Infrastructure is more<br />than servers. It's <span>trust.</span></h2><p className="section-text">DevOps/Cloud Engineer with hands-on experience automating and deploying scalable cloud infrastructure on AWS. I bring together CI/CD, containers, infrastructure as code and observability to make software delivery reliable from commit to customer.</p><div className="social-row"><a href="https://www.linkedin.com/in/aman-gill" target="_blank" rel="noreferrer" data-testid="linkedin-link"><Linkedin size={17} /> LinkedIn <ExternalLink size={13} /></a><a href="https://github.com/aman-gill" target="_blank" rel="noreferrer" data-testid="github-link"><Github size={17} /> GitHub <ExternalLink size={13} /></a><button onClick={() => setContactOpen(true)} data-testid="private-contact-button"><Mail size={17} /> Private contact <ArrowUpRight size={13} /></button></div></div></div></section>
      <section className="container section" id="experience"><div className="section-heading"><p className="section-kicker">02 / EXPERIENCE</p><p className="section-note">A track record of making<br />complex things feel simple.</p></div><div className="timeline">{experience.map((item, i) => <article className="timeline-item" key={item.role} data-testid={`experience-item-${i}`}><div className="timeline-marker">0{i + 1}</div><div className="timeline-main"><div className="timeline-top"><div><h3>{item.role}</h3><p>{item.company}</p></div><time>{item.date}</time></div><ul>{item.points.map(point => <li key={point}>{point}</li>)}</ul></div></article>)}</div></section>
      <section className="skills-section"><div className="container skills-grid"><div><p className="section-kicker">03 / TOOLKIT</p><h2>The tools behind<br /><span>the calm.</span></h2></div><div className="skill-list">{skills.map((skill, i) => <span key={skill} data-testid={`skill-${i}`}>{skill}</span>)}</div></div></section>
      <section className="container section projects-section" id="projects"><div className="section-heading"><p className="section-kicker">04 / SELECTED WORK</p><p className="section-note">Practical systems.<br />Measurable outcomes.</p></div><div className="project-grid">{projects.map((project, i) => <article className="project-card" key={project.title} data-testid={`project-card-${i}`}><div className="project-number">0{i + 1}</div><p className="project-label">{project.label}</p><h3>{project.title}</h3><p>{project.text}</p><div className="tag-row">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><ArrowUpRight className="project-arrow" size={22} /></article>)}</div></section>
      <section className="education container"><div><p className="section-kicker">05 / EDUCATION & CREDENTIALS</p><h2>Always learning.<br /><span>Always improving.</span></h2></div><div className="credential-list"><div className="credential"><CheckCircle2 /><div><h3>B.Tech, Computer Science Engineering</h3><p>Delhi Technological University · Dec 2024</p><strong>GPA 8.40 / 10</strong></div></div><div className="credential"><CheckCircle2 /><div><h3>AWS Certified Cloud Practitioner</h3><p>Cloud fundamentals, security and architecture</p></div></div><div className="credential"><CheckCircle2 /><div><h3>DevOps Certification — StarAgile</h3><p>CI/CD · Docker · Kubernetes · Internship completion</p></div></div></div></section>
      <section className="cta-section"><div className="container cta-inner"><p className="section-kicker">06 / GET IN TOUCH</p><h2>Have a system<br />worth <em>building?</em></h2><button className="button-light" onClick={() => setContactOpen(true)} data-testid="cta-contact-button">Start a conversation <ArrowUpRight size={17} /></button><p className="privacy-note">Direct contact details are kept private. Use the secure inquiry form to reach Aman.</p></div></section>
    </main><footer className="footer container"><span>© 2025 Aman Gill</span><span>DevOps · Cloud · Reliability</span><span>Built with intention <span className="blue-dot">●</span></span></footer>
    {contactOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" data-testid="contact-modal"><div className="contact-modal"><button className="modal-close" onClick={() => setContactOpen(false)} aria-label="Close contact form" data-testid="close-contact-modal"><X /></button>{sent ? <div className="success-state"><CheckCircle2 size={44} /><h2>Message received.</h2><p>Thanks for reaching out. Aman will get back to you soon.</p><button className="button-primary" onClick={() => { setSent(false); setContactOpen(false); }} data-testid="close-success-button">Done</button></div> : <><p className="section-kicker">PRIVATE INQUIRY</p><h2>Let's connect.</h2><p className="modal-subtitle">Your message goes directly to Aman without exposing personal contact details.</p><form onSubmit={submitInquiry} data-testid="contact-form"><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" data-testid="contact-name-input" /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" data-testid="contact-email-input" /></label><label>Message<textarea required rows="4" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell me a little about the opportunity..." data-testid="contact-message-input" /></label><button className="button-primary full-button" type="submit" data-testid="contact-submit-button">Send inquiry <ArrowUpRight size={17} /></button></form></>}</div></div>}
  </div>;
}
export default App;